---
- name: Deployer l'application Angular
  hosts: aws
  become: true

  tasks:
    - name: Installer Nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Demarrer et activer Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Deployer l'application Angular
      ansible.builtin.copy:
        src: app/olympic-games-starter/
        dest: /usr/share/nginx/html/
        owner: nginx
        group: nginx

    - name: Deployer la configuration Nginx
      ansible.builtin.copy:
        src: files/angular.conf
        dest: /etc/nginx/conf.d/angular.conf
        owner: root
        group: root
        mode: "0644"
      notify: Redemarrer Nginx

  handlers:
    - name: Redemarrer Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted